version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/firebase/functions"
    schedule:
      interval: "daily"
